"""
PDF Report Generator — professional downloadable report.
Uses fpdf2 with Unicode sanitization for Helvetica compatibility.
"""
from fpdf import FPDF
from datetime import datetime
import config


# ── Unicode → ASCII safe replacements ─────────────────────────────
def _clean(text: str) -> str:
    """
    Replace Unicode characters that Helvetica cannot render.
    Keeps the text readable without needing external font files.
    """
    if not text:
        return ""
    replacements = {
        "\u2014": "-",    # em dash —
        "\u2013": "-",    # en dash –
        "\u2022": "*",    # bullet •
        "\u2019": "'",    # right single quote '
        "\u2018": "'",    # left single quote '
        "\u201C": '"',    # left double quote "
        "\u201D": '"',    # right double quote "
        "\u2192": "->",   # right arrow →
        "\u2190": "<-",   # left arrow ←
        "\u2713": "OK",   # check mark ✓
        "\u2717": "X",    # cross ✗
        "\u2610": "[ ]",  # ballot box ☐
        "\u2611": "[x]",  # ballot box checked ☑
        "\u00e9": "e",    # é
        "\u00e8": "e",    # è
        "\u00e0": "a",    # à
        "\u00fc": "u",    # ü
        "\u00f6": "o",    # ö
        "\u00e4": "a",    # ä
        "\u2026": "...",  # ellipsis …
        "\u00b7": "-",    # middle dot ·
        "\u2212": "-",    # minus sign −
        "\u00a0": " ",    # non-breaking space
        "\u2764": "<3",   # heart ❤
        "\u2665": "<3",   # heart suit ♥
        "\u25b6": ">",    # play button ▶
        "\u2705": "OK",   # white check mark ✅
        "\u274c": "X",    # cross mark ❌
        "\u26a0": "!",    # warning ⚠
        "\u2b50": "*",    # star ⭐
        "\u1f4aa": "",    # emoji 💪 — just remove
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)

    # Final pass — remove any remaining non-latin1 characters
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class SkillProbeReport(FPDF):
    """Custom PDF with branded header and footer."""

    def header(self):
        self.set_fill_color(10, 10, 15)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(99, 102, 241)
        self.cell(0, 12, "SKILLPROBE  -  Skill Assessment Report", align="C")
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        self.cell(
            0, 8,
            f"Page {self.page_no()}  |  Generated by SkillProbe  |  "
            f"{datetime.today().strftime('%B %d, %Y')}",
            align="C",
        )

    def section_title(self, text: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(99, 102, 241)
        self.set_fill_color(18, 18, 30)
        self.cell(0, 10, _clean(text), ln=True, fill=True)
        self.set_draw_color(99, 102, 241)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def body(self, text: str, color=(226, 232, 240)):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, _clean(text))
        self.ln(2)

    def kv(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(148, 163, 184)
        self.cell(55, 7, _clean(key) + ":", ln=False)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(226, 232, 240)
        self.multi_cell(0, 7, _clean(str(value)))

    def add_dark_page(self):
        self.add_page()
        self.set_fill_color(10, 10, 15)
        self.rect(0, 0, 210, 297, "F")
        self.ln(5)


def generate_pdf(
    gap_analysis:       dict,
    learning_plan:      dict,
    assessment_results: list,
    jd_parsed:          dict,
    resume_parsed:      dict,
) -> bytes:
    """Build and return the PDF report as bytes."""

    pdf = SkillProbeReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(10, 20, 10)

    # ══════════════════════════════════════════════════════════════
    # PAGE 1 — Cover
    # ══════════════════════════════════════════════════════════════
    pdf.add_dark_page()

    score     = gap_analysis.get("readiness_score", 0)
    pct       = round(score * 100)
    weeks     = gap_analysis.get("hire_ready_weeks", "?")
    candidate = _clean(resume_parsed.get("name", "Candidate"))
    role      = _clean(jd_parsed.get("title", "Target Role"))

    if score >= 0.70:
        score_color = (16, 185, 129)
    elif score >= 0.50:
        score_color = (245, 158, 11)
    else:
        score_color = (239, 68, 68)

    pdf.ln(25)

    # Logo text
    pdf.set_font("Helvetica", "B", 40)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 20, "SkillProbe", align="C", ln=True)

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, "Skill Assessment Report", align="C", ln=True)

    # Big score
    pdf.ln(15)
    pdf.set_font("Helvetica", "B", 80)
    pdf.set_text_color(*score_color)
    pdf.cell(0, 35, f"{pct}%", align="C", ln=True)

    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 8, "Overall Job Readiness", align="C", ln=True)

    # Details
    pdf.ln(15)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(226, 232, 240)
    for line in [
        f"Candidate:  {candidate}",
        f"Target Role:  {role}",
        f"Hire-Ready Estimate:  {weeks} weeks",
        f"Date:  {datetime.today().strftime('%B %d, %Y')}",
    ]:
        pdf.cell(0, 9, line, align="C", ln=True)

    # ══════════════════════════════════════════════════════════════
    # PAGE 2 — Assessment Summary
    # ══════════════════════════════════════════════════════════════
    pdf.add_dark_page()
    pdf.section_title("  Assessment Summary")

    obs = gap_analysis.get("overall_observation", "")
    if obs:
        pdf.body(obs)
        pdf.ln(3)

    pdf.kv("Readiness Score",  f"{pct}%")
    pdf.kv("Hire-Ready In",    f"{weeks} weeks")
    pdf.kv("Claim Accuracy",   gap_analysis.get("claim_accuracy_summary", ""))
    pdf.kv("Skills Assessed",  str(len(assessment_results)))

    pdf.ln(6)
    pdf.section_title("  Skill Breakdown")

    # Table header
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.set_fill_color(18, 18, 30)
    cols = [
        ("Skill",     48),
        ("Required",  25),
        ("Claimed",   25),
        ("Assessed",  25),
        ("Gap",       20),
        ("Accuracy",  47),
    ]
    for label, w in cols:
        pdf.cell(w, 8, label, border=0, fill=True)
    pdf.ln()

    for s in gap_analysis.get("skill_breakdown", []):
        gap_val = s.get("gap", 0)
        if gap_val <= 0.10:
            row_color = (16, 185, 129)
        elif gap_val <= 0.25:
            row_color = (245, 158, 11)
        else:
            row_color = (239, 68, 68)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*row_color)
        pdf.cell(48, 7, _clean(str(s.get("skill", "")))[:26])
        pdf.set_text_color(226, 232, 240)
        pdf.cell(25, 7, f"{s.get('required', 0):.0%}")
        pdf.cell(25, 7, f"{s.get('claimed',  0):.0%}")
        pdf.cell(25, 7, f"{s.get('assessed', 0):.0%}")
        pdf.set_text_color(*row_color)
        pdf.cell(20, 7, f"{gap_val:.0%}")
        pdf.set_text_color(226, 232, 240)
        pdf.cell(47, 7, _clean(str(s.get("claim_accuracy", "")))[:24])
        pdf.ln()

    # Strengths / Gaps / Quick Wins
    pdf.ln(6)
    col_w = 60

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(16, 185, 129)
    pdf.cell(col_w, 8, "Strengths")
    pdf.set_text_color(239, 68, 68)
    pdf.cell(col_w, 8, "Critical Gaps")
    pdf.set_text_color(245, 158, 11)
    pdf.cell(col_w, 8, "Quick Wins")
    pdf.ln()

    s_list = gap_analysis.get("strengths",     [])
    g_list = gap_analysis.get("critical_gaps", [])
    q_list = gap_analysis.get("quick_wins",    [])
    rows   = max(len(s_list), len(g_list), len(q_list), 1)

    pdf.set_font("Helvetica", "", 9)
    for i in range(rows):
        pdf.set_text_color(16, 185, 129)
        pdf.cell(col_w, 7, ("+ " + _clean(s_list[i])) if i < len(s_list) else "")
        pdf.set_text_color(239, 68, 68)
        pdf.cell(col_w, 7, ("! " + _clean(g_list[i])) if i < len(g_list) else "")
        pdf.set_text_color(245, 158, 11)
        pdf.cell(col_w, 7, ("-> " + _clean(q_list[i])) if i < len(q_list) else "")
        pdf.ln()

    # ══════════════════════════════════════════════════════════════
    # PAGE 3+ — Learning Plan
    # ══════════════════════════════════════════════════════════════
    pdf.add_dark_page()
    pdf.section_title("  Personalised Learning Plan")

    summary = learning_plan.get("summary", "")
    if summary:
        pdf.body(summary)

    pdf.kv("Total Weeks",   str(learning_plan.get("total_estimated_weeks", "?")))
    pdf.kv("Total Hours",   str(learning_plan.get("total_estimated_hours", "?")))
    pdf.kv("Schedule",      learning_plan.get("weekly_schedule", ""))
    pdf.ln(5)

    for phase in learning_plan.get("phases", []):
        # New page if near bottom
        if pdf.get_y() > 240:
            pdf.add_dark_page()

        phase_title = _clean(phase.get("title", "Phase"))
        phase_weeks = phase.get("duration_weeks", "?")

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(0, 9, f"{phase_title}  ({phase_weeks} weeks)", ln=True)
        pdf.set_draw_color(30, 30, 53)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

        for sk in phase.get("skills", []):
            if pdf.get_y() > 245:
                pdf.add_dark_page()

            skill_name = _clean(sk.get("skill", ""))
            curr_lvl   = _clean(sk.get("current_level", ""))
            tgt_lvl    = _clean(sk.get("target_level",  ""))
            hours      = sk.get("estimated_hours", "?")

            # Skill header
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(226, 232, 240)
            pdf.cell(
                0, 8,
                f"  {skill_name}  |  {curr_lvl} -> {tgt_lvl}  |  ~{hours} hrs",
                ln=True,
            )

            # Adjacent foundation
            adjacent = _clean(sk.get("adjacent_foundation", ""))
            if adjacent:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(148, 163, 184)
                pdf.set_x(15)
                pdf.multi_cell(180, 6, adjacent)

            # Why now
            why = _clean(sk.get("why_now", ""))
            if why:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(148, 163, 184)
                pdf.set_x(15)
                pdf.multi_cell(180, 6, why)

            # Milestones
            milestones = sk.get("milestones", [])
            if milestones:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(99, 102, 241)
                pdf.set_x(15)
                pdf.cell(0, 7, "Milestones:", ln=True)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(226, 232, 240)
                for m in milestones:
                    pdf.set_x(20)
                    pdf.multi_cell(175, 6, _clean(f"[ ]  {m}"))

            # Project
            project = _clean(sk.get("hands_on_project", ""))
            if project:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(16, 185, 129)
                pdf.set_x(15)
                pdf.cell(0, 7, "Project:", ln=True)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(226, 232, 240)
                pdf.set_x(20)
                pdf.multi_cell(175, 6, project)

            # Resources
            resources = sk.get("resources", [])
            if resources:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(99, 102, 241)
                pdf.set_x(15)
                pdf.cell(0, 7, "Resources:", ln=True)
                for r in resources[:3]:
                    title = _clean(r.get("title", ""))[:55]
                    url   = _clean(r.get("url",   ""))
                    pdf.set_font("Helvetica", "", 9)
                    pdf.set_text_color(99, 102, 241)
                    pdf.set_x(20)
                    pdf.cell(0, 6, f"->  {title}", ln=True)
                    if url:
                        pdf.set_x(25)
                        pdf.set_font("Helvetica", "", 8)
                        pdf.set_text_color(100, 116, 139)
                        pdf.multi_cell(170, 5, url)

            pdf.ln(3)

    # ── Closing note ───────────────────────────────────────────────
    if pdf.get_y() > 250:
        pdf.add_dark_page()

    pdf.ln(5)
    note = learning_plan.get("motivation_note", "")
    if note:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(16, 185, 129)
        pdf.multi_cell(0, 7, _clean(note))

    return bytes(pdf.output())